name: IOS

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build on ios
    runs-on: macos
    
    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: mkdir build
    - name: cmake
      run: cd build ; .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=../cmake_module/ios.toolchain.cmake -DPLATFORM=SIMULATOR64 -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: xcodebuild -scheme ALL_BUILD -configuration Release
